from .segmentation_hsv import instance as hsv
from .hsv_cc import instance as hsv_cc
from .hsv_sw import instance as hsv_sw
from .hsv_cc_tm import instance as hsv_cc_tm
from .hsv_sw_tm import instance as hvs_sw_tm
from .hsv_tm import instance as hvs_tm
from .hsv_cc_template import instance as hsv_cc_template
from .hsv_convolution import instance as hsv_convolution
from .hsv_integral import instance as hsv_integral
from .glob_template import instance as glob_template
